In [126]:
from sklearn.preprocessing import (
    StandardScaler, MinMaxScaler, RobustScaler, MaxAbsScaler, Normalizer,
    LabelEncoder, OneHotEncoder, OrdinalEncoder, LabelBinarizer,
    PolynomialFeatures, KBinsDiscretizer, 
    FunctionTransformer, PowerTransformer, QuantileTransformer, SplineTransformer, Binarizer, MultiLabelBinarizer
)
import numpy as np

In [127]:
# SCALING

In [128]:
'''
Standard Scaler:

formula: z = (x - mean) / std

Works well for:
- Logistic Regression
- Linear Regression
- SVM
- Neural Networks
- KNN
- PCA

When NOT ideal
- If data contains many outliers.

'''

X = np.array([[10], [20], [30], [40]])
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

X_original = scaler.inverse_transform(X_scaled) # To reverse the scaling and get back the original data
print(X_original)

[[-1.34164079]
 [-0.4472136 ]
 [ 0.4472136 ]
 [ 1.34164079]]
[[10.]
 [20.]
 [30.]
 [40.]]


In [129]:
'''
min-max scaler:

formula: z = (x - min) / (max - min)

Works well for:
Exact range of data is known and outliers are not present.
- Neural Networks
- Image Processing
- Deep Learning

When NOT ideal
- Very sensitive to outliers. Outliers can skew the min and max values, leading to distorted scaling of the data.

'''

X = np.array([[10], [20], [30], [40]])
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[0.        ]
 [0.33333333]
 [0.66666667]
 [1.        ]]


In [130]:
'''
Robust Scaler:

formula: z = (x - median) / IQR

Works well for:
- Data with outliers
- Data that is not normally distributed

When NOT ideal
- If data is normally distributed and does not contain outliers, other scalers like Standard Scaler may be more appropriate.

'''

X = np.array([[10], [20], [30], [40], [1000]])
scaler = RobustScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[-1. ]
 [-0.5]
 [ 0. ]
 [ 0.5]
 [48.5]]


In [131]:
'''
MaxAbs Scaler:

formula: z = x / max(abs(x))

Works well for:
- Data that is already centered around zero and has a known maximum absolute value.
- Sparse data (e.g., text data represented as word counts)
- Data that is not normally distributed

When NOT ideal
- If data contains outliers, as it can be sensitive to them.
- If data is not centered around zero, as it may not effectively scale the data.

'''

X = np.array([[-10], [-5], [0], [5], [10]])
scaler = MaxAbsScaler()
X_scaled = scaler.fit_transform(X)
print(X_scaled)

[[-1. ]
 [-0.5]
 [ 0. ]
 [ 0.5]
 [ 1. ]]


In [132]:
'''
normalizer:

formula: z = x / ||x||

Works well for:
- Data that is not normally distributed
- Data that is on different scales
- Text data represented as word counts

When NOT ideal
- If data is already on the same scale, as it may not provide any additional benefit.

'''

X = np.array([
    [3, 4],
    [1, 2],
    [10, 10]
])
normalizer = Normalizer()
X_scaled = normalizer.fit_transform(X)
print(X_scaled)

[[0.6        0.8       ]
 [0.4472136  0.89442719]
 [0.70710678 0.70710678]]


In [133]:
# ENCODING

In [134]:
# Label Encoding:

le = LabelEncoder()
data = ["Male", "Female", "Male", "Transgender"]
encoded = le.fit_transform(data)
print(encoded)

# Best for: A pair of categorical values (binary classification) where the order of the values does not matter.

[1 0 1 2]


In [135]:
# One-Hot Encoding:

X = np.array([["red"], ["blue"], ["green"], ["red"]])
ohe = OneHotEncoder(sparse_output=False)
X_encoded = ohe.fit_transform(X)
print(X_encoded)

# best for: Categorical variables with more than two categories, where the order of the categories does not matter.

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [136]:
# Ordinal Encoding:

X = np.array([
    ["small"],
    ["medium"],
    ["large"],
    ["medium"]
])

oe = OrdinalEncoder(categories=[["small", "medium", "large"]])
X_encoded = oe.fit_transform(X)
print(X_encoded)

# Best for: Categorical variables with more than two categories, where the order of the categories matters.

[[0.]
 [1.]
 [2.]
 [1.]]


In [137]:
# Label Binarizer:

y = ["yes", "no", "yes", "no"]
lb = LabelBinarizer()
y_encoded = lb.fit_transform(y)
print(y_encoded)

[[1]
 [0]
 [1]
 [0]]


In [138]:
'''
Feature Generation:

When to use
- Linear Regression
- Logistic Regression
- Curve fitting

'''

poly = PolynomialFeatures(degree=3)
X = [[1], [2], [3]]
X_poly = poly.fit_transform(X)
print(X_poly)

[[ 1.  1.  1.  1.]
 [ 1.  2.  4.  8.]
 [ 1.  3.  9. 27.]]


In [139]:
'''
KBins Discretizer:

When to use
- Credit scoring
- Risk analysis
- Age grouping

'''
X = [[18], [25], [40], [60], [80]]
kbd = KBinsDiscretizer(
    n_bins=3,
    encode="ordinal",
    strategy="uniform"
)
print(kbd.fit_transform(X))

[[0.]
 [0.]
 [1.]
 [2.]
 [2.]]


In [140]:
'''
Function Transformer:

When useful: 
- Logarithmic transformation

'''
transformer = FunctionTransformer(np.log1p)
X = [[1], [10], [100]]
print(transformer.fit_transform(X))

[[0.69314718]
 [2.39789527]
 [4.61512052]]


In [141]:
'''
Power Transformer:

When useful:
- When the data has a skewed distribution
- When the data has a non-normal distribution

When to use:
- Linear Regression
- Logistic Regression
- Statistical models

'''
pt = PowerTransformer()
X_transformed = pt.fit_transform(X)
print(X_transformed)

[[-1.20252235]
 [-0.04329681]
 [ 1.24581916]]


In [142]:
'''
Quantile Transformer:

When to use:
- Extreme outliers
- Non-normal distributions
'''

qt = QuantileTransformer()
X_new = qt.fit_transform(X)

c:\Learning_ML\venv\lib\site-packages\sklearn\preprocessing\_data.py:2846: UserWarning: n_quantiles (1000) is greater than the total number of samples (3). n_quantiles is set to n_samples.
  warnings.warn(


In [143]:
'''
Spline Transformer:

Used in
- Time series
- Forecasting
- Smooth nonlinear relationships

'''
spline = SplineTransformer(n_knots=4)
X_new = spline.fit_transform(X)

In [144]:
'''
Binarizer:

When to use
- Presence/absence
- Boolean features
- Rule-based systems
'''

b = Binarizer(threshold=5)
print(b.fit_transform([[2], [5], [8], [12]]))

[[0]
 [0]
 [1]
 [1]]


In [145]:
'''
MultiLabel Binarizer:

Used in:
- Tags
- Genres
- Recommendations
'''

mlb = MultiLabelBinarizer()
data = [
    ["Action", "Comedy"],
    ["Drama"],
    ["Action", "Drama"]
]
print(mlb.fit_transform(data))

[[1 1 0]
 [0 0 1]
 [1 0 1]]
