In [29]:
import numpy as np

In [30]:
# 1D array
a = np.array([1, 2, 3, 4])
print(a.dtype)   # int64
print(a.shape)   # (4,)

# 2D array (matrix)
m = np.array([[1, 2], [3, 4]])
print(m.shape)   # (2, 2)

# Specify dtype
f = np.array([1, 2, 3], dtype=np.float32)

int64
(4,)
(2, 2)


In [31]:
np.zeros(5)                  # [0. 0. 0. 0. 0.]
np.zeros((3, 4))             # 3×4 matrix of zeros

np.ones((2, 3))              # 2×3 matrix of ones
np.ones_like(m)               # same shape as m, filled 1
np.zeros_like(m)              # same shape as m, filled 0

np.full_like(m, 99)          # same shape as m, filled 99
np.full((3, 3), 7)           # 3×3 matrix of 7s

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [ ]:
np.eye(3)
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]

np.eye(3, k=1)   # ones on the 1st super-diagonal

# diag: extract diagonal OR build diagonal matrix
m = np.array([[1,2],[3,4]])
np.diag(m)          # [1, 4]  — extract
np.diag([1,2,3])   # 3×3 diagonal matrix

In [33]:
# arange: like Python range but returns ndarray
np.arange(10)           # [0 1 2 ... 9]
np.arange(2, 10, 2)     # [2 4 6 8]
np.arange(0, 1, 0.25)   # [0.   0.25 0.5  0.75]

# linspace: N evenly-spaced points between start & stop
np.linspace(0, 1, 5)    # [0.   0.25 0.5  0.75 1. ]
np.linspace(0, 10, 100) # 100 points from 0 to 10
np.logspace(0, 3, 4)    # [1. 10. 100. 1000.]

array([   1.,   10.,  100., 1000.])

In [34]:
a = np.array([[1,2,3],[4,5,6]])

a.shape     # (2, 3)
a.ndim      # 2 — number of dimensions
a.size      # 6 — total elements
a.dtype     # dtype('int64')
a.itemsize  # 8 — bytes per element
a.nbytes    # 48 — total bytes
a.T         # transpose (shape becomes (3,2))

array([[1, 4],
       [2, 5],
       [3, 6]])

In [35]:
np.info(np.dot)       # full docstring
# np.lookfor('sort')    # search for functions by keyword

# Check array properties
np.isnan(a).any()    # any NaN?
np.isinf(a).any()    # any Inf?
np.isfinite(a).all() # all finite?
np.isreal(a).all()   # all real numbers?

dot(a, b, out=None)

Dot product of two arrays. Specifically,

- If both `a` and `b` are 1-D arrays, it is inner product of vectors
  (without complex conjugation).

- If both `a` and `b` are 2-D arrays, it is matrix multiplication,
  but using :func:`matmul` or ``a @ b`` is preferred.

- If either `a` or `b` is 0-D (scalar), it is equivalent to
  :func:`multiply` and using ``numpy.multiply(a, b)`` or ``a * b`` is
  preferred.

- If `a` is an N-D array and `b` is a 1-D array, it is a sum product over
  the last axis of `a` and `b`.

- If `a` is an N-D array and `b` is an M-D array (where ``M>=2``), it is a
  sum product over the last axis of `a` and the second-to-last axis of
  `b`::

    dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])

It uses an optimized BLAS library when possible (see `numpy.linalg`).

Parameters
----------
a : array_like
    First argument.
b : array_like
    Second argument.
out : ndarray, optional
    Output argument. This must have the exact kind that would be re

np.True_

In [36]:
a = np.arange(12)        # shape: (12,)

a.reshape(3, 4)          # (3, 4)  — view if possible
a.reshape(2, 3, 2)        # (2, 3, 2)
a.reshape(3, -1)          # -1 infers missing dim → (3,4)

a.ravel()                 # 1D view (no copy if possible)
a.flatten()               # 1D copy (always new array)

# Add/remove dimensions
a.reshape(1, -1)          # row vector (1, 12)
a[:, np.newaxis]          # column vector (12, 1)
np.expand_dims(a, axis=0) # same as above
np.squeeze(a)             # remove size-1 dimensions

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.concatenate([a, b], axis=0)   # stack rows  → (4,2)
np.concatenate([a, b], axis=1)   # stack cols  → (2,4)

np.vstack([a, b])  # vertical  → (4,2)
np.hstack([a, b])  # horizontal → (2,4)

# stack: adds a NEW axis
np.stack([a, b], axis=0)   # (2,2,2)
np.stack([a, b], axis=2)   # (2,2,2) — different axis

# Split back apart
np.split(a, 2, axis=0)    # [array([[1,2]]), array([[3,4]])]

[array([[1, 2]]), array([[3, 4]])]

In [38]:
a = np.arange(24).reshape(2, 3, 4)

a.T                           # reverse all axes → (4,3,2)
np.transpose(a)               # same
np.transpose(a, (0, 2, 1))   # custom order → (2,4,3)

np.swapaxes(a, 1, 2)         # swap axes 1 and 2 → (2,4,3)

# Commonly used in ML for (batch, H, W, C) → (batch, C, H, W)
img = np.random.rand(32, 64, 64, 3)
img_t = np.transpose(img, (0, 3, 1, 2))  # (32,3,64,64)

In [39]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

a[0, 1]       # 2  — element at row 0, col 1
a[1]          # [4 5 6]  — entire row 1
a[:, 2]       # [3 6 9]  — entire column 2
a[0:2, 1:3]   # [[2,3],[5,6]]  — sub-matrix
a[::2, ::2]   # [[1,3],[7,9]] — every other row/col
a[-1]         # [7 8 9]  — last row

array([7, 8, 9])

In [40]:
a = np.array([10, 20, 30, 40, 50])

# Boolean mask
mask = a > 25              # [F F T T T]
a[mask]                    # [30 40 50]
a[a % 20 == 0]            # [20 40]

# Fancy indexing (pick by index)
a[[0, 2, 4]]               # [10 30 50]

# np.where — conditional selection
np.where(a > 25, a, -1)  # [-1 -1 30 40 50]
np.where(a > 25)          # (array([2, 3, 4]),) — indices

# np.nonzero — indices of non-zero elements
np.nonzero(a > 25)        # same as above

(array([2, 3, 4]),)

In [41]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b       # [5 7 9]
a - b       # [-3 -3 -3]
a * b       # [4 10 18]
a / b       # [0.25 0.4  0.5]
a ** 2      # [1 4 9]
a % 2       # [1 0 1]
a // 2      # [0 1 1]

# Broadcasting: scalar applies to all
a * 10      # [10 20 30]
a + 100     # [101 102 103]

array([101, 102, 103])

In [42]:
a = np.array([0, np.pi/2, np.pi])

# Trig
np.sin(a)        # [0. 1. 0.]
np.cos(a)        # [1. 0. -1.]
np.tan(a)

# Exponential & Log
np.exp([0, 1, 2])       # [1.   2.71 7.39]
np.log([1, np.e, 10])  # [0. 1. 2.30]
np.log2([1, 2, 8])     # [0. 1. 3.]
np.log10([1,10,100])   # [0. 1. 2.]

# Other ufuncs
np.sqrt([1, 4, 9])      # [1. 2. 3.]
np.abs([-1, -2, 3])    # [1 2 3]
np.floor([1.9, 2.1])   # [1. 2.]
np.ceil([1.1, 2.9])    # [2. 3.]
np.round([1.567], 2)  # [1.57]

array([1.57])

In [43]:
a = np.array([-3, 0, 2, 7, 15])

np.clip(a, 0, 10)   # [0  0  2  7 10]  — clamp to [0,10]
np.sign(a)           # [-1  0  1  1  1]
np.diff(a)           # [3  2  5  8]  — a[i+1] - a[i]
np.diff(a, n=2)     # second-order differences
np.cumsum(a)         # cumulative sum
np.cumprod([1,2,3]) # [1 2 6]

array([1, 2, 6])

In [44]:
a = np.array([[1,2,3],[4,5,6]])

a.sum()          # 21  — total sum
a.sum(axis=0)   # [5 7 9]  — column sums
a.sum(axis=1)   # [6 15]   — row sums

a.mean()         # 3.5
a.mean(axis=0)  # [2.5 3.5 4.5]

a.min()  ; a.max()
a.argmin(); a.argmax()     # index of min/max
a.std()  ; a.var()         # std dev, variance

np.median(a)               # 3.5
np.percentile(a, 75)      # 75th percentile
np.quantile(a, [0.25, 0.75])  # Q1 and Q3

array([2.25, 4.75])

In [45]:
a = np.array([1, 2, 2, 3, 3, 3, 4])

# Unique values and counts
np.unique(a)                        # [1 2 3 4]
vals, counts = np.unique(a, return_counts=True)
# vals=[1,2,3,4]  counts=[1,2,3,1]

# Count occurrences per integer value
np.bincount(a)   # [0 1 2 3 1]  (index = value)

# Histogram
counts, edges = np.histogram(a, bins=4)
# counts=[1 2 3 1], edges=[1. 1.75 2.5 3.25 4.]

In [46]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

np.dot(a, b)       # matrix multiply
np.matmul(a, b)    # same (preferred for matrices)
a @ b              # @ operator — same, cleanest syntax

# Dot product of vectors
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
np.dot(u, v)       # 32  (scalar)

# Element-wise vs matrix multiply
a * b              # element-wise  (Hadamard)
a @ b              # matrix multiply

array([[19, 22],
       [43, 50]])

In [47]:
A = np.array([[3,1],[1,2]])

np.linalg.det(A)          # determinant: 5.0
np.linalg.inv(A)          # inverse matrix
np.linalg.matrix_rank(A)  # rank: 2
np.linalg.norm(A)         # Frobenius norm
np.linalg.norm(A, ord=1) # L1 norm

# Eigenvalues and eigenvectors
vals, vecs = np.linalg.eig(A)

# Singular Value Decomposition
U, S, Vt = np.linalg.svd(A)

# Solve Ax = b
b = np.array([9, 8])
x = np.linalg.solve(A, b)  # solution vector

In [48]:
u = np.array([3.0, 4.0])

np.linalg.norm(u)        # 5.0  — L2 / Euclidean
np.linalg.norm(u, 1)    # 7.0  — L1 / Manhattan
np.linalg.norm(u, np.inf) # 4.0 — L∞ / max norm

# Cross product (3D vectors)
a = np.array([1,0,0])
b = np.array([0,1,0])
np.cross(a, b)           # [0 0 1]

# Outer product
np.outer([1,2,3], [1,2,3])
# [[1 2 3]
#  [2 4 6]
#  [3 6 9]]

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [49]:
rng = np.random.default_rng(seed=42)  # recommended API

# Uniform [0, 1)
rng.random(5)
rng.random((3, 3))

# Integers
rng.integers(0, 10, size=6)   # [0, 10)

# Normal (Gaussian)
rng.normal(loc=0, scale=1, size=1000)

# Other distributions
rng.uniform(0, 5, size=10)
rng.binomial(n=10, p=0.5, size=5)
rng.poisson(lam=3, size=5)
rng.exponential(scale=2, size=5)

array([3.20241091, 0.49784672, 0.51909487, 6.16819366, 1.83725004])

In [50]:
rng = np.random.default_rng(42)
a = np.arange(10)

# Shuffle in-place
rng.shuffle(a)

# Permutation (returns new array)
rng.permutation(10)          # random perm of 0..9
rng.permutation(a)           # random perm of a

# Choice — sample from array
rng.choice(a, size=3)                  # with replacement
rng.choice(a, size=3, replace=False)   # without replacement
rng.choice(a, size=3, p=a/45)         # weighted sampling

array([7, 8, 8])

In [51]:
a = np.array([1, 5, 3, 7, 2])
b = np.array([2, 5, 1, 4, 8])

a == b    # [F T F F F]
a > b     # [F F T T F]
a >= b    # [F T T T F]

np.logical_and(a > 2, a < 6)   # [F T T F F]
np.logical_or(a < 2, a > 5)    # [T F F T F]
np.logical_not(a > 3)          # [T F T F T]

np.any(a > 5)   # True
np.all(a > 0)   # True
np.allclose(a, b, atol=1e-8)  # float comparison

False

In [52]:
a = np.array([3, 1, 4, 1, 5, 9, 2])

np.sort(a)               # [1 1 2 3 4 5 9]  — copy
a.sort()                 # in-place sort
np.sort(a)[::-1]        # descending sort

# argsort: returns indices that would sort the array
np.argsort(a)            # [1 3 6 0 2 4 5]

# 2D: sort along axis
m = np.array([[3,1],[4,2]])
np.sort(m, axis=1)      # sort each row

# Binary search in sorted array
np.searchsorted([1,3,5,7], 4)  # 2 — insert position

np.int64(2)

In [53]:
a = np.array([1, 2, 3, 4])
b = np.array([3, 4, 5, 6])

np.isin(a, b)             # [F F T T]  — membership test
np.isin(a, b)             # same but supports ND arrays

np.intersect1d(a, b)      # [3 4]
np.union1d(a, b)          # [1 2 3 4 5 6]
np.setdiff1d(a, b)        # [1 2]  — in a but not b
np.setxor1d(a, b)         # [1 2 5 6]  — exclusive or

array([1, 2, 5, 6])

In [54]:
# Rule: dimensions align from RIGHT to LEFT.
# Compatible if same OR one of them is 1.

a = np.ones((3, 4))  # shape (3,4)
b = np.ones(4)       # shape   (4,)  → broadcasts to (3,4)
(a + b).shape         # (3, 4) ✓

# Common pattern: add column vector to matrix
col = np.array([[1],[2],[3]])  # (3,1)
m   = np.ones((3, 4))         # (3,4)
(m + col).shape                # (3,4) ✓

# Outer product via broadcasting
r = np.arange(3)[:, np.newaxis]  # (3,1)
c = np.arange(3)[np.newaxis, :]  # (1,3)
(r + c)  # (3,3) addition table

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [55]:
a = np.arange(12).reshape(3, 4)

# Binary .npy (fast, lossless)
np.save('array.npy', a)
loaded = np.load('array.npy')

# Multiple arrays in .npz
np.savez('data.npz', x=a, y=a*2)
data = np.load('data.npz')
data['x']  # retrieve by name

# Text format (CSV-like)
np.savetxt('array.csv', a, delimiter=',', fmt='%.2f')
np.loadtxt('array.csv', delimiter=',')

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [56]:
a = np.array([1, 2, 3], dtype=np.int32)

# Cast to different dtype
a.astype(np.float64)    # new array with float64
a.astype('complex')    # string alias works too

# Copy vs View
b = a.copy()            # independent copy
c = a.view()            # shared memory (changes affect a)
c = a[:]                # also a view (not a copy!)

# Check if array owns its data
a.flags['OWNDATA']      # True for a, False for view
np.shares_memory(a, c)  # True for view

True