In [30]:
import torch
import numpy as np

In [ ]:
print(torch.__version__)

2.5.1+cu121


In [32]:
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))
else:
    print("no")

NVIDIA GeForce RTX 4050 Laptop GPU


In [33]:
t = torch.tensor([1, 2, 3, 4])
print(t)          # tensor([1, 2, 3, 4])
print(t.dtype)    # torch.int64

# 2D tensor (matrix)
m = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
print(m.shape)    # torch.Size([2, 2])

# Specify dtype explicitly
t = torch.tensor([1, 2, 3], dtype=torch.float32)

# From NumPy array (shares memory!)
import numpy as np
arr = np.array([1.0, 2.0, 3.0])
t = torch.from_numpy(arr)

tensor([1, 2, 3, 4])
torch.int64
torch.Size([2, 2])


In [34]:
torch.zeros(3, 4)             # 3×4 tensor of 0s
torch.ones(2, 3)              # 2×3 tensor of 1s
torch.full((2, 3), 7.0)       # 2×3 tensor of 7.0
torch.empty(3, 3)             # uninitialized (garbage values)

# _like versions: match shape & dtype of existing tensor
t = torch.tensor([[1.0, 2.0], [3.0, 4.0]])
torch.zeros_like(t)            # same shape, filled 0
torch.ones_like(t)             # same shape, filled 1
torch.full_like(t, 99.0)      # same shape, filled 99

tensor([[99., 99.],
        [99., 99.]])

In [35]:
# arange: evenly spaced integers
torch.arange(10)                  # tensor([0,1,...,9])
torch.arange(2, 10, 2)           # tensor([2, 4, 6, 8])
torch.arange(0, 1, 0.25)         # tensor([0., .25, .5, .75])

# linspace: N evenly-spaced floats between start & end
torch.linspace(0, 1, 5)          # tensor([0., .25, .5, .75, 1.])

# eye: identity matrix
torch.eye(3)
# tensor([[1., 0., 0.],
#         [0., 1., 0.],
#         [0., 0., 1.]])

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [36]:
# Uniform [0, 1)
torch.rand(3, 4)

# Standard normal (mean=0, std=1)
torch.randn(3, 4)

# Random integers
torch.randint(0, 10, size=(3, 4))   # values in [0, 10)

# Reproducible results with a seed
torch.manual_seed(42)
t = torch.rand(3, 3)

# _like versions
torch.rand_like(t)    # same shape, random uniform
torch.randn_like(t)   # same shape, random normal

tensor([[ 0.3930,  0.4327, -1.3627],
        [ 1.3564,  0.6688, -0.7077],
        [-0.3267, -0.2788, -0.4220]])

In [37]:
t = torch.randn(2, 3, 4)

t.shape            # torch.Size([2, 3, 4])
t.size()           # same as .shape
t.ndim             # 3  — number of dimensions
t.numel()          # 24 — total number of elements
t.dtype            # torch.float32
t.device           # device(type='cpu')

# Check specific dimension
t.shape[0]         # 2
t.size(1)          # 3

# Is it on GPU?
t.is_cuda          # False (if on CPU)
t.is_contiguous()  # True if memory layout is C-contiguous

True

In [38]:
t = torch.tensor([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0]])

t.sum()              # tensor(21.)
t.sum(dim=0)        # tensor([5., 7., 9.])  — column sums
t.sum(dim=1)        # tensor([6., 15.])    — row sums

t.mean()             # tensor(3.5)
t.mean(dim=1)       # tensor([2., 5.])

t.max()              # tensor(6.)
t.min()              # tensor(1.)
t.argmax()           # tensor(5)  — flat index
t.argmax(dim=1)     # tensor([2, 2])  — col index of max per row

t.std()              # standard deviation
t.var()              # variance
t.median()           # median value

tensor(3.)

In [39]:
t = torch.arange(12).reshape(3, 4)
# tensor([[ 0,  1,  2,  3],
#         [ 4,  5,  6,  7],
#         [ 8,  9, 10, 11]])

t[0]            # first row:   tensor([0, 1, 2, 3])
t[1, 2]         # element [1,2]: tensor(6)
t[:, 1]         # second col:  tensor([1, 5, 9])
t[0:2, 1:3]     # sub-matrix
t[-1]           # last row

# Get scalar value from a single-element tensor
t[0, 0].item()  # Python int/float: 0

0

In [40]:
t = torch.tensor([10, 20, 30, 40, 50])

# Boolean mask
mask = t > 25                   # tensor([F, F, T, T, T])
t[mask]                          # tensor([30, 40, 50])
t[t % 20 == 0]                 # tensor([20, 40])

# torch.where — conditional selection
torch.where(t > 25, t, torch.zeros_like(t))
# tensor([ 0,  0, 30, 40, 50])

# Index tensor (fancy indexing)
idx = torch.tensor([0, 2, 4])
t[idx]                           # tensor([10, 30, 50])

# nonzero: indices of True elements
torch.nonzero(t > 25)          # tensor([[2],[3],[4]])

tensor([[2],
        [3],
        [4]])

In [41]:
t = torch.arange(12)           # shape (12,)

t.reshape(3, 4)                 # (3, 4)  — copy if needed
t.view(3, 4)                    # (3, 4)  — view (must be contiguous)
t.reshape(3, -1)                # -1 infers dim → (3, 4)
t.reshape(2, 2, 3)              # (2, 2, 3)

t.flatten()                      # always 1D
t.reshape(-1)                   # same as flatten

# Add / remove dimensions
t.unsqueeze(0)                  # (1, 12) — insert dim at position 0
t.unsqueeze(1)                  # (12, 1)
t.unsqueeze(0).squeeze(0)       # remove dim of size 1

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [42]:
a = torch.zeros(2, 3)
b = torch.ones(2, 3)

# cat: join along existing axis
torch.cat([a, b], dim=0)       # (4, 3) — stack rows
torch.cat([a, b], dim=1)       # (2, 6) — stack cols

# stack: creates a NEW axis
torch.stack([a, b], dim=0)     # (2, 2, 3)
torch.stack([a, b], dim=1)     # (2, 2, 3) different axis

# split: divide into chunks of given size
t = torch.arange(12).reshape(6, 2)
chunks = torch.split(t, 2, dim=0)   # 3 tensors of shape (2,2)

# chunk: divide into N equal pieces
torch.chunk(t, 3, dim=0)             # 3 tensors of shape (2,2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[ 8,  9],
         [10, 11]]))

In [43]:
t = torch.randn(2, 3, 4)

# permute: reorder ALL dimensions
t.permute(0, 2, 1)             # (2, 4, 3)
t.permute(2, 0, 1)             # (4, 2, 3)

# transpose: swap two dimensions
t.transpose(1, 2)              # (2, 4, 3)

# .T shortcut for 2D tensors
m = torch.randn(3, 4)
m.T                             # (4, 3)

# After permute/transpose the tensor may not be contiguous
# Call .contiguous() before .view()
t.permute(2, 0, 1).contiguous().view(-1)

tensor([ 3.3832e-01, -1.3407e+00,  1.0669e+00,  1.8775e-01, -1.3109e-03,
         3.4987e-01,  1.6992e+00, -5.8537e-01, -4.5015e-01, -3.5762e-01,
        -3.0360e-01,  6.1728e-01,  1.0868e-02,  5.3619e-01, -6.7875e-01,
        -3.1651e-01, -9.8644e-01, -1.6933e-01, -3.3874e-01,  5.2462e-01,
         5.7432e-01,  5.8863e-01,  1.2330e-01,  2.3323e-01])

In [44]:
a = torch.tensor([1.0, 2.0, 3.0])
b = torch.tensor([4.0, 5.0, 6.0])

a + b                 # tensor([5., 7., 9.])
a - b                 # tensor([-3., -3., -3.])
a * b                 # tensor([ 4., 10., 18.])  element-wise
a / b                 # tensor([0.25, 0.40, 0.50])
a ** 2                # tensor([1., 4., 9.])

# Equivalent torch functions
torch.add(a, b)
torch.sub(a, b)
torch.mul(a, b)
torch.div(a, b)

# In-place versions (modify tensor directly, saves memory)
a.add_(b)             # a = a + b  (trailing _ = in-place)
a.mul_(2.0)          # a = a * 2

tensor([10., 14., 18.])

In [45]:
t = torch.tensor([-2.0, 0.0, 1.0, 4.0])

torch.exp(t)           # e^x
torch.log(t)           # natural log (NaN for negatives)
torch.log2(t)
torch.log10(t)
torch.sqrt(t)          # square root
torch.abs(t)           # tensor([2., 0., 1., 4.])
torch.sign(t)          # tensor([-1., 0., 1., 1.])
torch.ceil(t)
torch.floor(t)
torch.round(t)

# clamp: restrict values to [min, max]
torch.clamp(t, min=0.0, max=3.0)   # tensor([0., 0., 1., 3.])

# Trigonometry
torch.sin(t); torch.cos(t); torch.tanh(t)

tensor([-0.9640,  0.0000,  0.7616,  0.9993])

In [46]:
t = torch.tensor([[1.0, 2.0], [3.0, 4.0]])

# Global reductions → scalar
t.sum()              # tensor(10.)
t.prod()             # tensor(24.)
t.mean()             # tensor(2.5)
t.max()              # tensor(4.)
t.min()              # tensor(1.)

# Along a dimension
t.sum(dim=0)         # tensor([4., 6.])  — column sums
t.sum(dim=1)         # tensor([3., 7.])  — row sums

# keepdim=True preserves shape for broadcasting
t.sum(dim=1, keepdim=True)    # tensor([[3.],[7.]])

# max/min return (values, indices) when dim specified
vals, idx = t.max(dim=1)      # max per row + its index

In [47]:
# Scalar broadcast
t = torch.ones(3, 4)
t + 10                          # adds 10 to every element

# Row vector broadcast over matrix
row = torch.tensor([[1.0, 2.0, 3.0, 4.0]])  # (1, 4)
mat = torch.ones(3, 4)                          # (3, 4)
(mat + row).shape                                # (3, 4) ✓

# Column vector broadcast
col = torch.tensor([[1.0], [2.0], [3.0]])     # (3, 1)
(mat + col).shape                                # (3, 4) ✓

# Rule: dimensions align from RIGHT, compatible if equal or one is 1
# (3,4) + (4,) → (3,4)  ✓
# (3,4) + (3,) → ERROR  ✗ — use (3,1) instead

torch.Size([3, 4])

In [48]:
a = torch.tensor([3, 1, 4, 1, 5])
b = torch.tensor([2, 2, 2, 2, 2])

a == b             # tensor([F, F, T, F, F])
a > b              # element-wise greater than
a >= b
torch.eq(a, b)     # same as ==

torch.any(a > 3)  # tensor(True)
torch.all(a > 0)  # tensor(True)

# Sort
sorted_t, indices = torch.sort(a)            # ascending
sorted_t, indices = torch.sort(a, descending=True)

# Top-k values
vals, idx = torch.topk(a, k=3)             # 3 largest

In [49]:
a = torch.randn(3, 4)
b = torch.randn(4, 5)

# 2D matrix multiply
torch.mm(a, b)             # (3, 5)  — only 2D
torch.matmul(a, b)         # (3, 5)  — supports ND
a @ b                      # @ operator — cleanest syntax

# Batched matrix multiply
A = torch.randn(10, 3, 4)  # batch of 10 matrices
B = torch.randn(10, 4, 5)
torch.bmm(A, B)            # (10, 3, 5)

# Dot product (1D tensors)
u = torch.tensor([1.0, 2.0, 3.0])
v = torch.tensor([4.0, 5.0, 6.0])
torch.dot(u, v)            # tensor(32.) — scalar

tensor(32.)

In [50]:
A = torch.tensor([[3.0, 1.0], [1.0, 2.0]])

torch.linalg.det(A)          # determinant: 5.0
torch.linalg.inv(A)          # inverse matrix
torch.linalg.matrix_rank(A)  # rank: 2
torch.linalg.norm(A)         # Frobenius norm
torch.linalg.norm(A, ord=1) # L1 norm

# Eigenvalues and eigenvectors
vals, vecs = torch.linalg.eig(A)

# Singular Value Decomposition
U, S, Vh = torch.linalg.svd(A)

# Solve Ax = b
b = torch.tensor([9.0, 8.0])
x = torch.linalg.solve(A, b)  # solution vector

In [51]:
#  Enable gradient tracking
x = torch.tensor([2.0, 3.0], requires_grad=True)

# Build a computation graph
y = x ** 2         # y = x²
z = y.sum()        # z = sum(x²)

# Backpropagate — compute dz/dx
z.backward()

print(x.grad)      # tensor([4., 6.])  — dz/dx = 2x

# Gradients accumulate! Zero them before next pass
x.grad.zero_()

# Disable gradient tracking (e.g. during inference)
with torch.no_grad():
    result = x ** 2   # no graph built, faster

# Or use .detach() to get a copy without grad history
x_no_grad = x.detach()

tensor([4., 6.])


In [52]:
x = torch.tensor([1.0, 2.0], requires_grad=True)
y = x * 3

# Check if a tensor has a grad function
print(x.grad_fn)        # None (leaf tensor)
print(y.grad_fn)        # MulBackward0
print(y.requires_grad)  # True (inherited)

# Detach from computation graph
y_detached = y.detach()           # new tensor, no grad
print(y_detached.requires_grad)   # False

# Disable grad globally for inference (fastest)
with torch.no_grad():
    pred = model(x)

# Permanently disable grad on a tensor
x.requires_grad_(False)  # in-place

None
True
False


NameError: name 'model' is not defined

In [53]:
# Check if CUDA is available
print(torch.cuda.is_available())    # True/False
print(torch.cuda.device_count())    # number of GPUs
print(torch.cuda.get_device_name(0)) # GPU name

# Create tensor directly on GPU
t = torch.zeros(3, 3, device='cuda')

# Move existing tensor to GPU
t = torch.randn(3, 3)
t_gpu = t.to('cuda')           # or t.cuda()

# Move back to CPU
t_cpu = t_gpu.to('cpu')        # or t_gpu.cpu()

# Device-agnostic code (best practice)
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
t = t.to(device)

True
1
NVIDIA GeForce RTX 4050 Laptop GPU


In [55]:
# Tensor → NumPy (shares memory if on CPU!)
t = torch.tensor([1.0, 2.0, 3.0])
arr = t.numpy()               # np.ndarray
t.add_(1)                    # modifies arr too!

# NumPy → Tensor (also shares memory)
arr = np.array([4.0, 5.0, 6.0])
t = torch.from_numpy(arr)

# To avoid shared memory, use .copy() or .clone()
arr_copy = t.numpy().copy()   # independent NumPy copy
t_copy   = t.clone()          # independent tensor copy

# GPU tensors must be moved to CPU first
t_gpu = torch.randn(3, device='cuda')
arr = t_gpu.cpu().numpy()

In [56]:
# Most common dtypes
torch.float32   # 32-bit float  — default for floats, most ML
torch.float64   # 64-bit float  — high precision (numpy default)
torch.float16   # 16-bit float  — half precision (GPU training)
torch.bfloat16  # brain float16 — better range than float16
torch.int32     # 32-bit int
torch.int64     # 64-bit int    — default for ints
torch.bool      # boolean

# Create with specific dtype
t = torch.tensor([1, 2, 3], dtype=torch.float32)

# Cast to another dtype
t.float()               # → float32
t.double()              # → float64
t.int()                 # → int32
t.long()                # → int64
t.bool()                # → bool
t.to(torch.float16)     # explicit cast

tensor([1., 2., 3.], dtype=torch.float16)

In [57]:
t = torch.randn(3, 4)

# Save a single tensor
torch.save(t, 'tensor.pt')
t_loaded = torch.load('tensor.pt')

# Save multiple tensors as a dict
torch.save({'weights': t, 'biases': torch.zeros(4)}, 'data.pt')
checkpoint = torch.load('data.pt')
checkpoint['weights']    # retrieve by key

# Safe load (recommended in newer PyTorch)
t_loaded = torch.load('tensor.pt', weights_only=True)

# Move to correct device on load
t_loaded = torch.load('tensor.pt', map_location=torch.device('cpu'))

C:\Users\vivek\AppData\Local\Temp\ipykernel_141256\1595866678.py:5: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  t_loaded = torch.load('tensor.pt')
C:\Users\vivek\AppData\L